### ISSUE TITLE
MID360 と ZED で FAST-LIVO2

### ISSUE THREAD

**Issue by Ryusei-Baba** [Ryusei-Baba/FAST-LIVO2#1]
![image](https://github.com/user-attachments/assets/417898a7-068d-4f3c-a9b7-b2340d3fcf2f)

**Comment by Ryusei-Baba** [comment]
![Image](https://github.com/user-attachments/assets/0a71d3e2-7d0f-45ed-bf8f-1adb4855708b)

```
/**:
  ros__parameters:

    common:
      img_topic: "/zed_node/rgb/image_rect_color"  # カメラのトピック名
      lid_topic: "/livox/lidar"  # LiDARのトピック名
      imu_topic: "/livox/imu"  # IMUのトピック名
      img_en: 1  # カメラを使用する場合は1、有効化
      lidar_en: 1  # LiDARを使用する場合は1、有効化
      ros_driver_bug_fix: false  # ROSドライバの不具合修正を行う場合はtrue

    extrin_calib:  # 外部キャリブレーション
      extrinsic_T: [0.011, 0.02329, -0.04412]
      extrinsic_R: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0] 
      # カメラ-LiDAR間の外部パラメータ ZEDがMID360よりピッチ軸（y軸）に20度傾いている
      Rcl: [0.0,-1.0,0.0,
            0.3420,0.0,-0.9397,
            0.9397,0.0,0.3420] 
      Pcl: [0.11, 0.06, -0.07]          # 並進：ZEDがMID360より前に11cm、左に6cm、下に7cm

    time_offset:  # 時刻同期の調整
      imu_time_offset: 0.0
      img_time_offset: 0.1
      exposure_time_init: 0.0

    preprocess: 
      point_filter_num: 1
      filter_size_surf: 0.1 #点群をダウンサンプリング（フィルタリング）する際のサーフェス上のボクセルサイズ
      lidar_type: 1            # Livox MID360
      scan_line: 6
      blind: 0.8

    vio:
      max_iterations: 5 
      outlier_threshold: 1000 
      img_point_cov: 100
      patch_size: 4 
      patch_pyrimid_level: 3
      normal_en: true
      raycast_en: true
      inverse_composition_en: false
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: true
      imu_int_frame: 30 
      acc_cov: 0.5 
      gyr_cov: 0.3 
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001

    lio:
      max_iterations: 5
      dept_err: 0.02
      beam_err: 0.05
      min_eigen_value: 0.0025
      voxel_size: 0.3 # ローカルマップ用のボクセルグリッドサイズ
      max_layer: 2
      max_points_num: 150  # 各レイヤーにおける最大点数
      layer_init_num: [4, 4, 4, 4, 4]

    local_map:
      map_sliding_en: true
      half_map_size: 40 
      sliding_thresh: 3.0

    uav:
      imu_rate_odom: false
      gravity_align_en: false

    publish:
      dense_map_en: false
      pub_effect_point_en: false
      pub_plane_en: false 
      pub_scan_num: 1
      blind_rgb_points: 0.0

    evo:
      seq_name: "MID360_ZED_Test" 
      pose_output_en: false 

    pcd_save:  # PCDファイル出力の設定
      pcd_save_en: true  # PCDファイル保存の有効化
      colmap_output_en: false  # COLMAPフォーマットで出力（interval = -1が必要）
      filter_size_pcd: 0.1 
      interval: -1  
      # interval = -1 の場合はすべてのフレームを1つのPCDファイルに保存するため、メモリオーバーフローに注意
```
